### ISSUE TITLE
exclude_area and include_area are not valid arguments

### ISSUE THREAD

**Issue by DiSalvio** [teachbase/imatcher#9]
When I call
`Imatcher.compare("path/1", "path/2", exclude_area: [700, 800, 1500, 1000])` or `Imatcher.compare("path/1", "path/2", include_area: [700, 800, 1500, 1000])`

I get
`ArgumentError: unknown keyword: exclude_area` or
`ArgumentError: unknown keyword: include_area`

Pretty confused about this one because these two keywords are specifically mentioned in the wiki.

I'm testing this in the Pry console, after I got the same error trying to run it in my ruby/cucumber/watir testing stack:
`require 'imatcher'`
`Imatcher.compare(...)`

**Comment by DiSalvio** [comment]
@palkan is this project actively maintained? Will you (or some other maintainer) address the above issue or should I just look for a workaround?

Just asking because there haven't been any updates to the repo in a while.

**Comment by DiSalvio** [comment]
Okay after digging thru the code, I realized that the argument name should be `exclude_rect` or `include_rect`, not `exclude_area` or `include_area`...

So the actual issue is just the inconsistency between the argument names wiki and the argument names passed to your `attr_reader` in the Base class.

**Comment by Earendil95** [comment]
@DiSalvio yes, project is maintained. Thank you for an issue :)
Use `include_rect` and `exclude_rect` options and docs will be fixed soon
